# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Getting-Started' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Getting-Started
  pod 'Amplify'
  pod 'Amplify/Tools'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
end
